name: Build and Deploy
on:
   push:
      branches:
         - main
jobs:
   build-and-deploy:
      runs-on: ubuntu-latest
      steps:
         - name: Checkout 🛎️
           uses: actions/checkout@v2.3.1

         - name: Install and Build 🔧
           run: |
              yarn install
              yarn build
              yarn pkg

         - name: Deploy Pages 🚀
           uses: JamesIves/github-pages-deploy-action@4.1.5
           with:
              branch: gh-pages
              folder: dist/gh-pages

         - name: Deploy Package 🚀
           uses: JamesIves/github-pages-deploy-action@4.1.5
           with:
              branch: package
              folder: dist/package
